/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_EXAMPLES_E03_Methods_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_EXAMPLES_E03_Methods_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/examples/E03MethodsStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {
namespace examples {

/**
 * Provides a default implementation for E03MethodsStubRemoteEvent and
 * E03MethodsStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT E03MethodsStubDefault
    : public virtual E03MethodsStub {
public:
    COMMONAPI_EXPORT E03MethodsStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(E03Methods::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT E03MethodsStubRemoteEvent* initStubAdapter(const std::shared_ptr< E03MethodsStubAdapter> &_adapter) {
        CommonAPI::Stub<E03MethodsStubAdapter, E03MethodsStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void foo(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _x1, std::string _x2, fooReply_t _reply) {
        (void)_client;
        (void)_x1;
        (void)_x2;
        E03Methods::stdErrorTypeEnum error;
        int32_t y1 = 0;
        std::string y2 = "";
        _reply(error, y1, y2);
    }
    COMMONAPI_EXPORT virtual void fireMyStatusEvent(const int32_t &_myCurrentValue) {
        E03MethodsStub::fireMyStatusEvent(_myCurrentValue);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual E03MethodsStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(E03MethodsStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        E03MethodsStubDefault *defaultStub_;
    };
protected:
    E03MethodsStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace examples
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_2 = v1;

#endif // V1_COMMONAPI_EXAMPLES_E03_Methods_STUB_DEFAULT
